#!/bin/zsh

alias vim="nvim"
alias reload='source ~/.zshrc'
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'
alias tm='tmux new-session -n $(basename $PWD)'

alias dotfiles='vim -c "NERDTree ~/.dotfiles"'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}


function aws-ecr-login() {
 $(aws ecr get-login --no-include-email)
}
