#!/bin/zsh

alias vim="nvim"
alias reload='source ~/.zshrc'
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'

alias dotfiles='cd ~/.dotfiles; vim -c "NERDTree"'

# test
alias t='bundle exec rspec'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}


