#!/bin/zsh

# meta
alias reload='source ~/.zshrc'
alias ea='vim ~/.dot-files/aliases/aliases'
alias ega='vim ~/.dot-files/aliases/git'
alias erc='vim ~/.dot-files/zshrc'

# utility
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'
alias ..='cd ..'

alias dot-files='cd ./dot-files; vim'
alias e-scripts='cd ~/Work/Compass/sql-scripts; vim'
alias blog='cd ~/Workspace/Projects/davidkdickson.github.io; vim'
alias todo-personal='cd ~/Desktop/todo/todo_personal; vim '
alias todo-work='cd ~/Desktop/todo/todo_work; vim'
alias todo='cd ~/Desktop/todo/todo_personal; vim'

# test
alias t='bundle exec rspec'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}
