#!/bin/zsh

# meta
alias reload='source ~/.dot-files/.zshrc'
alias ea='vim ~/.dot-files/aliases/aliases'
alias ee='vim ~/.dot-files/zsh/env'
alias ega='vim ~/.dot-files/aliases/git'
alias erc='vim ~/.dot-files/zshrc'

# utility
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'
alias ..='cd ..'

alias dot-files='vim ~/.dot-files'
alias e-scripts='vim ~/Scripts'
alias blog='vim ~/Workspace/Projects/davidkdickson.github.io'
alias todo-personal='vim ~/Desktop/todo/todo_personal'
alias todo-work='vim ~/Desktop/todo/todo_work'
alias todo='vim -O ~/Desktop/todo/todo_personal ~/Desktop/todo/todo_work'

# test
alias t='bundle exec rspec'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}
