#!/bin/zsh

# meta
alias reload='source ~/.dot-files/.zshrc'
alias ea='atom ~/.dot-files/.aliases/aliases'
alias ee='atom ~/.dot-files/.zsh/env'
alias ega='atom ~/.dot-files/.aliases/git'
alias erc='atom ~/.dot-files/.zshrc'

# utility
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'
alias ..='cd ..'

# projects
alias comp='cd ~/Work/Compass'
alias ccore='cd ~/Work/Compass/CompassCore'
alias chub='cd ~/Work/Compass/CompassCoreHub'
alias cshared='cd ~/Work/Compass/compassshared'
alias e-scripts='atom ~/Scripts'
alias blog='cd ~/Workspace/Projects/davidkdickson.github.io'

# test
alias t='bundle exec rspec'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}
