#!/bin/zsh

# meta
alias reload='source ~/.dot-files/.zshrc'
alias ea='atom ~/.dot-files/.aliases/aliases'
alias ee='atom ~/.dot-files/.zsh/env'
alias ega='atom ~/.dot-files/.aliases/git'
alias erc='atom ~/.dot-files/.zshrc'

# utility
alias a='ls -A' # -A all except literal . ..
alias la="ls -A -l -G"
alias c='clear'
alias ..='cd ..'

alias dot-files='atom ~/.dot-files'
alias e-scripts='atom ~/Scripts'
alias blog='atom ~/Workspace/Projects/davidkdickson.github.io'
alias todo-personal='atom ~/Desktop/todo/todo_personal'
alias todo-work='atom ~/Desktop/todo/todo_work'
alias todo='vim -O ~/Desktop/todo/todo_personal ~/Desktop/todo/todo_work'

# test
alias t='bundle exec rspec'

function listening_port {
	lsof -n -i4TCP:$1 | grep LISTEN
}

function postgres {
	if [[ $1 == 'start' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log start
	fi

	if [[ $1 == 'stop' ]]; then
		pg_ctl -D /usr/local/var/postgres -l /usr/local/var/postgres/server.log stop
	fi
}
