#!/bin/#!/usr/bin/env zsh
IFS=$'\n'

# automatically load git aliases.
for al in `git config --get-regexp alias | cut -c 7-`; do
  gital=$(echo $al | awk '{print $1}')
  gitcmd=$(echo $al | awk '{$1=""; print substr($0,2)}')
  alias g$gital="git $gitcmd"
done
