#!/bin/zsh

# logs
alias gl='git log --oneline --decorate --all --graph'

alias g='git'
alias gs='git status -s'
alias ga='git add -A .'
alias gcm='git commit -m'
alias gcam='git commit -am'
alias gcamm='git commit -v -a --amend'
alias gpom='git push origin master'
alias gps='git push'
alias gpl='git pull'
alias gco='git checkout'
alias gb='git branch'

alias gdt='git difftool'
