#!/bin/zsh

alias g='git'

# logs
alias gl='git log --oneline --decorate --all --graph'
alias gll='gl --numstat'

# status in short format
alias gs='git status -s'

# add add changes from all tracked and untracked files
alias ga='git add --all .'

# merge without fast forwarding
alias gm='git merge --no-ff'

# branches
alias gb='git branch'
alias gbl='git branch --all'

alias gcm='git commit -m'
alias gcam='git commit -am'
alias gcamm='git commit -v -a --amend'
alias gps='git push'
alias gpl='git pull'
alias gco='git checkout'
