#!/bin/zsh

SESSION_NAME="work"

cd ~/Work/Compass

pid=$(lsof -i:4567 -t); kill -TERM $pid || kill -KILL $pid
pid=$(lsof -i:8080 -t); kill -TERM $pid || kill -KILL $pid
pid=$(lsof -i:9000 -t); kill -TERM $pid || kill -KILL $pid
pid=$(lsof -i:9001 -t); kill -TERM $pid || kill -KILL $pid
pid=$(lsof -i:9002 -t); kill -TERM $pid || kill -KILL $pid
pid=$(lsof -i:6379 -t); kill -TERM $pid || kill -KILL $pid

tmux has-session -t ${SESSION_NAME}

if [ $? != 0 ]
then
  cd ~/Work/Compass/CompassCore
  git checkout development
  tmux new -s ${SESSION_NAME} -d
  tmux split-window -v -p 30
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'gulp build --gulpfile ./core.client/gulpfile.js' C-m
  tmux send-keys -t 2 'gulp build --gulpfile ./core.client/gulpfile.js' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux send-keys -t 2 'rackup' C-m
  tmux rename-window 'Core'

  cd ~/Work/Compass/CompassReporting
  git checkout development
  tmux new-window
  tmux split-window -v -p 30
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux send-keys -t 2 'rackup' C-m
  tmux rename-window 'Reporting'

  cd ~/Work/Compass/LtvService
  git checkout development
  tmux new-window
  tmux split-window -v -p 30
  tmux split-window -h
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux send-keys -t 2 'rackup' C-m
  tmux send-keys -t 3 'redis-server' C-m
  tmux rename-window 'Ltv'

  cd ~/Work/Compass/RepurchaseRateService
  git checkout development
  tmux new-window
  tmux split-window -v -p 30
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux send-keys -t 2 'rackup' C-m
  tmux rename-window 'Repurchase'
  
  cd ~/Work/Compass/CompassShared
  git checkout master
  tmux new-window
  tmux split-window -v -p 30
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux rename-window 'Shared'


  cd ~/Work/Compass/CompassCoreHub
  git checkout master
  tmux new-window
  tmux split-window -v -p 30
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux send-keys -t 1 'git checkout development' C-m
  tmux send-keys -t 1 'git pull' C-m
  tmux send-keys -t 2 'bundle install' C-m
  tmux rename-window 'Hub'

  tmux select-window -t ${SESSION_NAME}:1
fi

tmux attach -t ${SESSION_NAME}
