#!/bin/zsh

COMPASS="/home/david/Work/compass"

cd $COMPASS

developer_setup () {
  cd $COMPASS/$1
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  service_path=$1
  new_name=$service_path[(ws:-:)1]
  tmux rename-window $new_name
}

split_setup () {
  cd $COMPASS/$1
  tmux new-window
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window $1
}

services_session () {
  SESSION_NAME="services"
  tmux has-session -t ${SESSION_NAME}

  if [ $? != 0 ]
  then
    cd $COMPASS/core

    tmux new -s ${SESSION_NAME} -d

    tmux split-window -v -p 30
    tmux select-pane -t 0
    tmux send-keys -t 0 'vim' C-m
    tmux rename-window 'core'

    developer_setup 'reporting-service'
    developer_setup 'clv-service'
    developer_setup 'repurchase-rate-service'
    developer_setup 'compass-shared'
    developer_setup 'scheduler'
    split_setup 'docker'

    tmux select-window -t ${SESSION_NAME}:1
  fi
}

collectors_session () {
  SESSION_NAME="collectors"

  tmux has-session -t ${SESSION_NAME}

  if [ $? != 0 ]
  then
    cd $COMPASS/hub

    tmux new -s ${SESSION_NAME} -d

    tmux split-window -v -p 30
    tmux select-pane -t 0
    tmux send-keys -t 0 'vim' C-m
    tmux rename-window 'hub'

    developer_setup 'bigcommerce-collector-service'
    developer_setup 'shopify-collector-service'
    developer_setup 'magento-collector-service'
    developer_setup 'googleanalytics-collector-service'
    developer_setup 'facebook-collector-service'
    developer_setup 'amazon-collector-service'
    developer_setup 'stripe-collector-service'
    developer_setup 'paypal-collector-service'
    developer_setup 'collector-common'
    developer_setup 'warren'
    split_setup 'docker'

    tmux select-window -t ${SESSION_NAME}:1
  fi
}

meetings_session () {
  SESSION_NAME="meetings"

  tmux has-session -t ${SESSION_NAME}

  if [ $? != 0 ]
  then
    cd ~/Dropbox/Work/meetings

    tmux new -s ${SESSION_NAME} -d

    tmux send-keys -t 0 'vim' C-m
    tmux rename-window 'meetings'

    cd ~/Dropbox/Personal/todo
    tmux new-window
    tmux send-keys -t 0 'todo' C-m
    tmux rename-window 'todo'
  fi
}

ops_session () {
  SESSION_NAME="ops"

  tmux has-session -t ${SESSION_NAME}

  if [ $? != 0 ]
  then
    cd $COMPASS/ops

    tmux new -s ${SESSION_NAME} -d

    tmux send-keys -t 0 'vim' C-m
    tmux rename-window 'ops'

    split_setup 'scripts'
    split_setup 'docker-images'
    split_setup 'parametor'
  fi
}
services_session
collectors_session
meetings_session
ops_session

tmux attach -t collectors
