#!/bin/zsh

SESSION_NAME="work"

cd ~/work/compass

tmux has-session -t ${SESSION_NAME}

if [ $? != 0 ]
then
  cd ~/work/compass/core
  tmux new -s ${SESSION_NAME} -d
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'core'

  cd ~/work/compass/reporting-service
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'reporting'

  cd ~/work/compass/ltv-service
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'ltv'

  cd ~/work/compass/repurchase-rate-service
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'repurchase'

  cd ~/work/compass/compass-shared
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'shared'

  cd ~/work/compass/hub
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'hub'

  cd ~/work/compass/magento-collector-service
  tmux new-window
  tmux split-window -v -p 30
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'magento'

  cd ~/work/compass/compass-scripts
  tmux new-window
  tmux split-window -h
  tmux select-pane -t 0
  tmux send-keys -t 0 'vim' C-m
  tmux rename-window 'scripts'

  tmux select-window -t ${SESSION_NAME}:1
fi

tmux attach -t ${SESSION_NAME}
